apiVersion: v1
kind: Pod
metadata:
  name: sample-web
  labels:
    app: sample-web
spec:
  containers:
  - name: web
    image: taikiuejo0730/sample-web:case1  

---
apiVersion: v1
kind: Service
metadata:
  name: sample-web
  labels:
    app: sample-web
spec:
  selector:
    app: sample-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80